sudo : required

language : generic

services : 
  - docker

before_install :
  - echo "start creating an image with dockerfile"
  - docker build -t knoa0405/docker-react-app -f Dockerfile.dev .

script :
  - docker run -e CI=true knoa0405/docker-react-app npm run test -- --coverage
  
deploy :
  provider : elasticbeanstalk
  region : "ap-northeast-2"
  app : "docker-react-app-test"
  env : "Dockerreactapptest-env"
  bucket_name : "elasticbeanstalk-ap-northeast-2-416263461894"
  bucket_path : "docker-react-app-test"
  on :
    branch : main

access_key_id : $AWS_ACCESS_KEY
secret_access_key : $AWS_SECRET_ACCESS_KEY